#!/usr/bin/env bash
# redirect nginx web server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
str_red="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/codedvictor permanent;"
sed -i "s/server_name _;/$str_red/" /etc/nginx/sites-enabled/default

sudo service nginx restart
