#!/usr/bin/env bash
# install nginx on the server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
string_red="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/codedvictor permanent;"
sudo sed -i "s/server_name _;/$string_red/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
string_red="listen 80 default_server;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$string_red/" /etc/nginx/sites-enabled/default

sudo service nginx restart
