#!/usr/bin/env bash
# install nginx on the server
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
str_red="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/codedvictor permanent;"
sudo sed -i "s/server_name _;/$str_red/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
str_cus="listen 80 default_server;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$str_cus/" /etc/nginx/sites-enabled/default

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

sudo service nginx restart
