#!/usr/bin/env bash
#Install and configure HAproxy load balancer on a server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\*

server_conf=\
"
frontend http
	 bind *:80
	 mode http
	 default_backend web-backend
backend web-backend
	balance roundrobin
	server 297636-web-01 54.144.249.223:80 check
	server 297636-web-02 54.90.38.102:80 check
"
echo "$server_conf" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
