#!/usr/bin/env bash
#Installation and configuration of HAproxy load balancer on a server
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get -y install haproxy=2.8.\*

server_conf=\
"
frontend http
	 bind *:80
	 mode http
	 default_backend web-backend
backend web-backend
	balance roundrobin
	server 297636-web-01 54.144.249.223:80 check
	server 297636-web-02 54.87.212.214:80 check
"
echo "$server_conf" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

msg="HAProxy configuration has been updated. Servers configured: $(grep -oP 'server \K\w+-\d+' /etc/haproxy/haproxy.cfg)"
echo "$msg"
