#!/usr/bin/env bash
# a bash script to debug an Ubuntu container's Nginx installation from listening on port 80
#sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
#sudo sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
#sudo sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
