#!/usr/bin/env bash
# case and while loop bash script display

i=0

while [ "$i" -lt 20 ];
do
	case "$i" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
	echo "$i"
done
