#!/usr/bin/env bash
# Shell script to display information about the school file

fl=school
if [ ! -e "$fl" ]
then
	echo "$fl file does not exist"
else
        echo "$fl file exists"
	if [ ! -s "$fl" ]
	then
		echo "$fl file is empty"
	else
		echo "$fl file is not empty"
	fi
	if [ -f "$fl" ]
	then
		echo "$fl is a regular file"
	fi
fi
