#!/usr/bin/env bash
# Configure the firewall for server web-01
# Block all incoming traffic by default
# Allow all outgoing traffic by default
# Allow SSH on port 22/443/80

sudo apt update
sudo apt install ufw

sudo systemctl enable ufw
sudo systemctl start ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
sudo ufw status
