#!/usr/bin/env bash
# Change the home IP Address and facebook IP Address
cp /etc/hosts ~/hosts.latest
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.latest
sed -i '2i8.8.8.8 facebook.com' ~/hosts.latest
cp ~/hosts.latest /etc/hosts
rm ~/hosts.latest
