#!/usr/bin/env bash
# bash script to fix the container so that Nginx is running as nginx user
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx start
